#!/usr/bin/env -S bash

grep() { /usr/bin/grep -i "$1"; }

ptrn1="dll"
ptrn2="touchpad"

dev_id="$(xinput list --long | grep "$ptrn1" | grep "$ptrn2" | awk '{ print $6 }' | sed 's/[=di]*//')"

xinput set-button-map "$dev_id" 1 0 3 4 5 6 7
